repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
    - id: isort
      args: ['-rc']
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      args: [--line-length=79, --target-version=py38]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      args: [--config-file=mypy.ini, --strict, --ignore-missing-imports, --no-implicit-reexport, app]